#!/bin/bash
set -euo pipefail

rm -rf build
mkdir build

cd src
zip -r ../build/zotero-excalidraw-1.0.0.xpi *
cd ../build

jq ".addons[\"zotero-excalidraw@zotero.org\"].updates[0].update_hash = \"sha256:`shasum -a 256 zotero-excalidraw-1.0.0.xpi | cut -d' ' -f1`\"" ../updates.json.tmpl > ../updates.json
